name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: huggingface/transformers-pytorch-gpu
    steps:
    - uses: actions/checkout@v2
    - name: Run pytest
      run: |
        poetry run pytest
